### ISSUE TITLE
Crash when using CameraInfo display

### ISSUE THREAD

**Issue by YoanSallami** [jsk-ros-pkg/jsk_visualization#713]
hello,

when using the camera info display, I have this message :
`̀``
rviz: /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/include/OgreAxisAlignedBox.h :252 : void Ogre::AxisAlignedBox::setExtents(const Ogre::Vector3&, const Ogre::Vector3&):  l'assertion « (min.x <= max.x && min.y <= max.y && min.z <= max.z) && "The minimum corner of the box must be less than or equal to maximum corner" » a échoué.
Abandon (core dumped)
```
Even when using the static_virtual_camera.py

Any idea on how to manage that ?

**Comment by iory** [comment]
Thank you for your report.

How to install jsk_rviz_plugins? By installing ```sudo apt install ros-kinetic-jsk-rviz-plugins```?

**Comment by k-okada** [comment]
if you're using
`/opt/ros/kinetic/lib/jsk_recognition_utils/static_virtual_camera.py`, you
need valid camera info parameters,
```
header:
  seq: 272
  stamp:
    secs: 1538704752
    nsecs: 969589948
  frame_id: "static_virtual_camera"
height: 768
width: 1024
distortion_model: ''
D: []
K: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
R: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
P: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
binning_x: 0
binning_y: 0
roi:
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```
--
◉ Kei Okada



2018年10月5日(金) 2:58 Yoan Sallami <notifications@github.com>:
