### ISSUE TITLE
RViz polygon blinking

### ISSUE THREAD

**Issue by stribor14** [jsk-ros-pkg/jsk_visualization#738]
Hello, I'm using the package version from Ubuntu 16.04 PPA (version 2.1.5-0xenial-20190320-184807-0800)

I'm trying to visualize the area which laser scan is covering with a polygon, and I'm using jsk polygon array with single polygon because your rviz plugin allows polygon to be filled with color.

When "only border" is selected, visualization behaves normally:

![image](https://user-images.githubusercontent.com/10760409/57462550-55f15780-7279-11e9-9712-cbc5d426d17a.png)

 But when a polygon is shown filled, everything starts to blink while randomly connecting some parts of a polygon (you can see overlap with transparency turned on):

![image](https://user-images.githubusercontent.com/10760409/57462595-6bff1800-7279-11e9-8575-009820a89c06.png)

**Comment by knorth55** [comment]
can you give us rosbag file to reproduce this issue or can you tell us how to reproduce your issue?

**Comment by stribor14** [comment]
Sorry, I changed the code, but the node was really simple. I've taken readings from the laser_scan topic of nav350 simulated in the Gazebo, then I've created a polygon in which I inserted all of the points laser has seen (range * sin/cos (angle)), sorted by angle. Polygons header is the same as a laser_scan header because I wanted 
same frame_id and timestamp.

**Comment by knorth55** [comment]
I have no idea because we cannot reproduce your problem in our environment.
but it seems that your sorting might be incorrect.

**Comment by YutoUchimi** [comment]
Although polygon in rviz does not blink, it is filled wrongly in some cases.

### case 1
```
<launch>
  <node name="polygon_array_publisher"
        pkg="jsk_recognition_utils" type="polygon_array_publisher.py">
    <rosparam>
      publish_rate: 10.0
      frame_id: map
      polygons:
        - points:
            - [3, 0, 0]
            - [4, 1, 0]
            - [1, 1, 0]
            - [1, 4, 0]
            - [0, 3, 0]
            - [-1, 4, 0]
            - [-1, 1, 0]
            - [-4, 1, 0]
            - [-3, 0, 0]
            - [-4, -1, 0]
            - [-1, -1, 0]
            - [-1, -4, 0]
            - [0, -3, 0]
            - [1, -4, 0]
            - [1, -1, 0]
            - [4, -1, 0]
          label: 0
          likelihood: 1.0
    </rosparam>
  </node>
</launch>
```
![polygon_wrongly_filled1](https://user-images.githubusercontent.com/22876283/63759186-0900c200-c8f8-11e9-8c65-e0624914616a.png)
![polygon_wrongly_filled2](https://user-images.githubusercontent.com/22876283/63759187-0900c200-c8f8-11e9-9f88-c98fb5bbe2e4.png)

### case 2
```
<launch>
  <node name="polygon_array_publisher"
        pkg="jsk_recognition_utils" type="polygon_array_publisher.py">
    <rosparam>
      publish_rate: 10.0
      frame_id: map
      polygons:
        - points:
            - [3, 0, 0]
            - [4, 1, 0]
            - [1, 1, 0]
            - [1, 4, 0]
            - [0, 3, 0]
            - [-1, 4, 0]
            - [-1, 1, 0]
            - [-4, 1, 0]
            - [-3, 0, 0]
          label: 0
          likelihood: 1.0
    </rosparam>
  </node>
</launch>
```
![polygon_wrongly_filled3](https://user-images.githubusercontent.com/22876283/63759400-66950e80-c8f8-11e9-9790-c599b87a0506.png)
![polygon_wrongly_filled4](https://user-images.githubusercontent.com/22876283/63759402-66950e80-c8f8-11e9-8548-21a852aceb0c.png)
